### ISSUE TITLE
Build Failed with current Version

### ISSUE THREAD

**Issue by dertuerke** [ngneat/overview#22]
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report 
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior
I have try to build, i get this error:
```
No matching export in "node_modules/@ngneat/overview/fesm2022/ngneat-overview.mjs" for import "DynamicViewModule"

    node_modules/@ngneat/hot-toast/fesm2022/ngneat-hot-toast.mjs:6:37:
      6 │ ...mplateRef, isComponent, DynamicViewModule } from '@ngneat/overvi...
```

## Environment

<pre><code>
Angular version: 17.0.5
 
For Tooling issues:
- Node version: v18
- Platform:  Mac

Packages:
"@angular/animations": "^17.0.5",
"@angular/common": "^17.0.5",
"@angular/compiler": "^17.0.5",
"@angular/core": "^17.0.5",
"@angular/forms": "^17.0.5",
"@angular/platform-browser": "^17.0.5",
"@angular/platform-browser-dynamic": "^17.0.5",
"@angular/router": "^17.0.5",
"@ngneat/dialog": "^5.0.0",
"@ngneat/hot-toast": "^6.0.1",
"@ngneat/overview": "^6.0.0",
"rxjs": "~7.8.1",
"tslib": "^2.6.2",
"zone.js": "~0.14.2"
</code></pre>

**Comment by NetanelBasal** [comment]
DynamicViewModule was converted to stanalone, you need to use DynamicViewDirective

**Comment by dertuerke** [comment]
I dont use `DynamicViewModule`. The error comes from the other package `hot-toast`.

**Comment by NetanelBasal** [comment]
Open the issue in the hot-toast repo. They need to update the peer deps https://github.com/ngneat/hot-toast/blob/master/projects/ngneat/hot-toast/package.json#L16.
